### ISSUE TITLE
After upgrading to 3.9.0, the project cannot be compiled.

### ISSUE THREAD

**Issue by AlexeyGorbunov** [OneSignal/OneSignal-XCFramework#29]
After updating to the latest version (3.9.0) an error occurs and it is not possible to compile the project.

**ERROR**
```
ld: warning: Could not find or use auto-linked framework 'OneSignal'
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_OneSignal", referenced from:
      objc-class-ref in NotificationService.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Xcode version**
13.1

**OneSignal-XCFramework iOS SDK version**
3.9.0

**Dependency Manager**
SPM

**Comment by Skovie** [comment]
same here

**Comment by j-j-m** [comment]
same thing over here

**Comment by j-j-m** [comment]
looks like a release came out 32 mins ago

**Comment by j-j-m** [comment]
yep. [3.9.1](https://github.com/OneSignal/OneSignal-XCFramework/releases/tag/3.9.1) fixes this

**Comment by Skovie** [comment]
I can confirm  the fix

**Comment by AlexeyGorbunov** [comment]
Thanks for the quick fix.
